### ISSUE TITLE
Single coord altitude / country

### ISSUE THREAD

**Issue by kumy** [urbanetic/srtm-server#1]
I have a fork of your project where I've added for my need new endpoints:
* for getting the altitude from a single coord pair
* for obtaining the country from a single coord pair.

Are you interested in such features, would you like a PR?

https://github.com/kumy/srtm-server#get-elevation-from-one-coordinate-pair

**Comment by aramk** [comment]
If it's backwards compatible, sure it's up to you.

**Comment by kumy** [comment]
It's backwards compatible.
